language: node_js
node_js:
  - "8.10"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
cache:
  npm: true
  directories:
    - node_modules

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod


after_success:
  - firebase deploy --token $FIREBASE_TOKEN

  deploy:
  provider: firebase
  skip-cleanup: true
  firebase-token: $FIREBASE_TOKEN
  keep-history: true
  local-dir: ./dist/Ci-example
  on:

notifications:
  email:
	recipients:
      - souradeep.mldt@gmail.com
      - souradeep.mldt@gmail.com
    on_success: never 
    on_failure: always
    

